"""Backup helper: extract the D:\\Thesis prompt history and index the paste cache.

Written as part of the docs/ai-knowledge portable backup. Read-only with respect
to every source location; it writes only inside docs/ai-knowledge/session-backup.
Kept in the backup so the extraction is reproducible rather than asserted.
"""

from __future__ import annotations

import datetime
import glob
import io
import json
import os
import sys

B = sys.argv[1]
HOME = os.environ["USERPROFILE"]
TARGET_PROJECT = "d:\\thesis"


def prompt_history() -> int:
    src = os.path.join(HOME, ".claude", "history.jsonl")
    dst = os.path.join(B, "session-backup", "prompt-history--D--Thesis.jsonl")
    n = 0
    with io.open(dst, "w", encoding="utf-8") as out:
        for line in io.open(src, encoding="utf-8", errors="replace"):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception:
                continue
            if (obj.get("project") or "").lower() == TARGET_PROJECT:
                out.write(json.dumps(obj, ensure_ascii=False) + "\n")
                n += 1
    return n


def paste_index() -> str:
    pdir = os.path.join(HOME, ".claude", "paste-cache")
    idx = os.path.join(B, "session-backup", "paste-cache", "INDEX.md")
    lines = [
        "# paste-cache index",
        "",
        "Source directory: `" + pdir + "`",
        "",
        "Raw text of large blocks the user pasted into Claude Code prompts. The",
        "`.txt` files beside this index are verbatim copies; this file is only a",
        "finding aid. Generated by `_backup_tools/mk_session_aux.py`.",
        "",
    ]
    for p in sorted(glob.glob(os.path.join(pdir, "*.txt")), key=os.path.getmtime):
        txt = io.open(p, encoding="utf-8", errors="replace").read()
        mt = datetime.datetime.fromtimestamp(os.path.getmtime(p))
        lines += [
            "## `" + os.path.basename(p) + "`",
            "- bytes: %d" % os.path.getsize(p),
            "- mtime: " + mt.isoformat(timespec="seconds"),
            "- opening text: " + " ".join(txt[:400].split()),
            "",
        ]
    io.open(idx, "w", encoding="utf-8").write("\n".join(lines))
    return idx


if __name__ == "__main__":
    print("prompt-history entries written:", prompt_history())
    print("wrote", paste_index())
